version: '3'

services:
  db:
    build: . 
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf/my.conf:/etc/mysql/conf.d/my.conf
      - ./data/:/data/

volumes:
  db-store:
